// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebAppMVCComboCascadeEF.Models;

[Table("T_Provincia")]
public partial class TProvincium
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [StringLength(50)]
    public string Nome { get; set; }

    [Column("idRegione")]
    public int? IdRegione { get; set; }

    public int? NumAbitanti { get; set; }

    [Column("isCapoluogo")]
    public bool? IsCapoluogo { get; set; }

    [ForeignKey("IdRegione")]
    [InverseProperty("TProvincia")]
    public virtual TRegione IdRegioneNavigation { get; set; }

    [InverseProperty("IdProvinciaNavigation")]
    public virtual ICollection<TComune> TComunes { get; set; } = new List<TComune>();
}